const {test,before,after,beforeEach}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
let browser,page;
before(async()=>{browser=await chromium.launch({headless:true,channel:process.env.OASIS_BROWSER_CHANNEL||'msedge'});});
after(async()=>{await browser?.close();});
beforeEach(async()=>{await page?.close();page=await browser.newPage({viewport:{width:1200,height:1000},timezoneId:'America/New_York'});await page.route('**/*',route=>route.abort());await page.setContent('<!doctype html><html lang="fr"><head><meta charset="utf-8"></head><body style="margin:20px;background:#1a1a17"></body></html>');await page.addScriptTag({content:fs.readFileSync(path.join(root,'dist/oasis-flightradar-card.js'),'utf8')});await page.addScriptTag({content:fs.readFileSync(path.join(__dirname,'fixture.js'),'utf8')});await page.evaluate(()=>{for(const view of document.querySelector('oasis-flightradar-card')._boardViews.values()){view.engine.animate=true;view.engine.rotate=true;const update=view.engine.update.bind(view.engine);view.engine.update=(values,message)=>update(values,message);}});});
test('Carte autonome : catalogue, fuseaux, tables et suivi',async()=>{
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card');return {airports:c._selector._airports.length,bourget:c._selector._airports.find(a=>a.code==='LFPB').name,local:c._localClock._zone,airport:c._airportClock._zone,rows:c.shadowRoot.querySelectorAll('tbody tr').length,flight:c.shadowRoot.querySelector('.followed').textContent,link:c.shadowRoot.querySelector('.followed a').href,calls:mockCalls.length};});
  assert.equal(result.airports,1153);assert.equal(result.bourget,'Paris Le Bourget');assert.equal(result.local,'America/New_York');assert.equal(result.airport,'Europe/Paris');assert.equal(result.rows,60);assert.match(result.flight,/OA101/);assert.match(result.link,/abcd1234/);assert.equal(result.calls,0);
});
test('Lecture seule : boutons et validation aéroport bloqués',async()=>{
  const result=await page.evaluate(async()=>{const c=document.querySelector('oasis-flightradar-card');c._openAction('clear');c._selector._open();c._selector._select('LHBP');await c._selector._save();return {disabled:[...c.shadowRoot.querySelectorAll('[data-action]')].every(b=>b.disabled),airport:c._selector._apply.disabled,dialog:c._dialog.open,calls:mockCalls.length};});assert.deepEqual(result,{disabled:true,airport:true,dialog:false,calls:0});
});
test('Recherche par nom/OACI/IATA, choix provisoire sans écriture',async()=>{
  for(const query of ['Le Bourget','LFPB','LBG']){const result=await page.evaluate(query=>{const c=document.querySelector('oasis-flightradar-card');c._selector._open();c._selector._search.value=query;c._selector._renderResults();return c._selector.shadowRoot.querySelector('.results').textContent;},query);assert.match(result,/LFPB/);}
  assert.equal(await page.evaluate(()=>mockCalls.length),0);
});
test('Actions uniquement après confirmation ; services simulés',async()=>{
  const result=await page.evaluate(async()=>{const c=mountCard({read_only:false});c._openAction('add');const before=mockCalls.length;c._input.value='oa123';await c._submitAction();c._openAction('remove');c._input.value='OA123';await c._submitAction();c._openAction('clear');await c._submitAction();c._selector._open();c._selector._select('LHBP');const provisional=mockCalls.length;await c._selector._save();return {before,provisional,calls:mockCalls};});
  assert.equal(result.before,0);assert.equal(result.provisional,3);assert.deepEqual(result.calls,[['text','set_value',{entity_id:'text.demo_add',value:'OA123'}],['text','set_value',{entity_id:'text.demo_remove',value:'OA123'}],['button','press',{entity_id:'button.demo_clear'}],['text','set_value',{entity_id:'text.demo_airport',value:'LHBP'}]]);
});
test('Code invalide, erreur de service et double validation',async()=>{
  const result=await page.evaluate(async()=>{const c=mountCard({read_only:false});c._openAction('add');c._input.value='<script>';await c._submitAction();const invalid=mockCalls.length;c._input.value='OA123';mockHass.callService=async()=>{throw Error('Test hors ligne');};await c._submitAction();const error=c.shadowRoot.querySelector('.feedback').textContent;const remains=c._dialog.open;let resolve;mockHass.callService=(...args)=>{mockCalls.push(args);return new Promise(r=>resolve=r);};const pending=c._submitAction();await c._submitAction();const during=mockCalls.length;resolve();await pending;return {invalid,error,remains,during,busy:c._busy};});assert.equal(result.invalid,0);assert.match(result.error,/Action impossible/);assert.equal(result.remains,true);assert.equal(result.during,1);assert.equal(result.busy,false);
});
test('Rendu mobile, dix lignes et en-têtes fixes',async()=>{
  await page.setViewportSize({width:390,height:900});
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card'),r=c.shadowRoot;return {overflow:document.documentElement.scrollWidth>innerWidth,boards:getComputedStyle(r.querySelector('.boards')).gridTemplateColumns.split(' ').length,scroll:r.querySelector('.scroll').clientHeight,max:getComputedStyle(r.querySelector('.scroll')).maxHeight,sticky:getComputedStyle(r.querySelector('th')).position,clock:c._localClock.getBoundingClientRect().width};});assert.equal(result.overflow,false);assert.equal(result.boards,1);assert.equal(result.max,'352px');assert.equal(result.sticky,'sticky');assert.ok(result.clock>100);
  await page.locator('oasis-fr24-internal-selector .launch').click();
  assert.equal(await page.locator('oasis-fr24-internal-selector dialog').evaluate(n=>n.getBoundingClientRect().right<=innerWidth),true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('oasis-fr24-internal-selector dialog').evaluate(n=>n.open),false);
});
test('Données manquantes, code inconnu et aucun HTML de capteur exécuté',async()=>{
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card');const states={...mockHass.states,'text.demo_airport':{state:'ZZZZ',attributes:{}},'sensor.demo_departures':{state:'1',attributes:{flights:[{airport_city:'<img src=x onerror="window.hacked=true">',flight_number:'XSS'}]}},'sensor.demo_arrivals':{state:'unavailable',attributes:{}}};c.hass={...mockHass,states};return {text:c.shadowRoot.querySelector('.boards').textContent,images:c.shadowRoot.querySelectorAll('.boards img').length,zone:c._airportClock._zone,calls:mockCalls.length};});assert.match(result.text,/Données indisponibles/);assert.match(result.text,/<img/);assert.equal(result.images,0);assert.equal(result.zone,null);assert.equal(result.calls,0);
});
test('Validation configuration, deux cartes et nettoyage horloges',async()=>{
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card');const errors=[];for(const extra of [{airport_entity:'light.test'},{visible_rows:0},{read_only:'false'},{airport_timezones:{LFPB:'Not/AZone'}},{local_images:{LFPB:{url:'javascript:alert(1)'}}}])try{c.setConfig({...mockConfig,...extra});}catch(e){errors.push(e.message);}const other=document.createElement('oasis-flightradar-card');other.setConfig({...mockConfig,airport_timezones:{LFPB:'Asia/Tokyo'}});other.hass=mockHass;document.body.append(other);const independent=[c._airportClock._zone,other._airportClock._zone];const clock=other._airportClock;other.remove();return {errors:errors.length,independent,clean:clock._timers.size,dialog:other._dialog.open};});assert.equal(result.errors,5);assert.deepEqual(result.independent,['Europe/Paris','Asia/Tokyo']);assert.equal(result.clean,0);assert.equal(result.dialog,false);
});
test('Éditeur conserve les options avancées',async()=>{
  const result=await page.evaluate(()=>{const editor=document.createElement('oasis-flightradar-card-editor');editor.setConfig({...mockConfig,airport_timezones:{LFPB:'Europe/Paris'}});document.body.append(editor);let last;editor.addEventListener('config-changed',e=>last=e.detail.config);const check=editor.shadowRoot.querySelector('input[type=checkbox]');check.checked=false;check.dispatchEvent(new Event('change'));return {read_only:last.read_only,zone:last.airport_timezones.LFPB};});assert.deepEqual(result,{read_only:false,zone:'Europe/Paris'});
});
test('Premier choix d’aéroport et bouton jamais utilisé',async()=>{
  const result=await page.evaluate(async()=>{mockHass.states['text.demo_airport']={state:'',attributes:{}};mockHass.states['button.demo_clear']={state:'unknown',attributes:{}};const c=mountCard({read_only:false});c._selector._open();c._selector._select('LFPB');const initial=c._selector._apply.disabled;await c._selector._save();const clearAvailable=c._actionAvailable('clear');return {initial,clearAvailable,calls:mockCalls.length};});assert.equal(result.initial,false);assert.equal(result.clearAvailable,true);assert.equal(result.calls,1);
});
test('Dix lignes complètes dans chaque tableau et heure selon le fuseau',async()=>{
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card'),scroll=c.shadowRoot.querySelector('.scroll');const header=c.shadowRoot.querySelector('thead').getBoundingClientRect().height;const row=c.shadowRoot.querySelector('tbody tr').getBoundingClientRect().height;const first=c.shadowRoot.querySelector('tbody td').textContent;const source=mockHass.states['sensor.demo_departures'].attributes.flights[0].time_scheduled_departure;const expected=new Intl.DateTimeFormat('fr-FR',{timeZone:'Europe/Paris',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(source*1000));return {complete:Math.floor((scroll.clientHeight-header)/row),first,expected};});assert.equal(result.complete,10);assert.equal(result.first,result.expected);
});
test('Panneaux : roue exacte, ligne suivante après la précédente, hors écran immédiat',async()=>{
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card');const flights=mockHass.states['sensor.demo_departures'].attributes.flights.map(f=>({...f,airport_city:'A'}));mockHass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'30',attributes:{flights}}}};c.hass=mockHass;c.shadowRoot.querySelector('.scroll').scrollIntoView();});
  await page.emulateMedia({reducedMotion:'no-preference'});
  const result=await page.evaluate(()=>{
    const c=document.querySelector('oasis-flightradar-card'),engine=c._boardViews.get('departures').engine;
    const flights=mockHass.states['sensor.demo_departures'].attributes.flights.map((f,i)=>({...f,airport_city:[0,1,29].includes(i)?'D':f.airport_city}));
    c.hass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'30',attributes:{flights}}}};
    const row=i=>engine.body.children[i].children[1].querySelector('.flap').dataset.char;
    const queue=engine.queue.map(j=>j.row.sectionRowIndex),trace=[];
    // Horloge synthétique : aucune attente ni service réel.
    for(const time of [0,70,140,210]){cancelAnimationFrame(engine.frame);engine.tick(time);trace.push(row(0));}
    const nextBefore=row(1),hidden=row(29);cancelAnimationFrame(engine.frame);engine.tick(280);const nextAfter=row(1);
    engine.stop();return {queue,trace,nextBefore,nextAfter,hidden,calls:mockCalls.length};
  });
  assert.deepEqual(result.queue,[0,1]);assert.deepEqual(result.trace,['B','C','D','D']);assert.equal(result.nextBefore,'A');assert.equal(result.nextAfter,'B');assert.equal(result.hidden,'D');assert.equal(result.calls,0);
});
test('Panneaux : boucle Z → 0 … 9 → : → - → vide → A et normalisation',async()=>{
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card');const flights=[{airport_city:'Z',flight_number:'A',status_text:'é-!'}];mockHass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'1',attributes:{flights}}}};c.hass=mockHass;c.shadowRoot.querySelector('.scroll').scrollIntoView();});
  await page.emulateMedia({reducedMotion:'no-preference'});
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card'),e=c._boardViews.get('departures').engine;c.hass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'1',attributes:{flights:[{airport_city:'A',flight_number:'A',status_text:'é-!'}]}}}};const trace=[];for(let i=0;i<14;i++){cancelAnimationFrame(e.frame);e.tick(i*70);trace.push(e.body.children[0].children[1].querySelector('.flap').dataset.char);}const normalized=[...e.body.children[0].children[3].querySelectorAll('.flap')].map(n=>n.dataset.char).join('');e.stop();return {trace,normalized};});
  assert.deepEqual(result.trace,['0','1','2','3','4','5','6','7','8','9',':','-',' ','A']);assert.equal(result.normalized,'E- ');
});
test('Panneaux : identité DOM, scroll conservé, arrêt hors zone et nettoyage',async()=>{
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card'),e=c._boardViews.get('departures').engine;e.scroll.scrollIntoView();const old=e.body.children[0];e.scroll.scrollTop=160;const position=e.scroll.scrollTop;const flights=mockHass.states['sensor.demo_departures'].attributes.flights.map(f=>({...f,airport_city:'ZZZZ'}));c.hass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'30',attributes:{flights}}}};const queued=e.queue.length;const same=old===e.body.children[0],preserved=e.scroll.scrollTop===position;e.scroll.scrollTop=850;e.scroll.dispatchEvent(new Event('scroll'));const onlyVisible=e.queue.every(j=>e.visible(j.row));c.remove();return {same,preserved,queued,onlyVisible,queue:e.queue.length,frame:e.frame};});assert.equal(result.same,true);assert.equal(result.preserved,true);assert.ok(result.queued>0);assert.equal(result.onlyVisible,true);assert.equal(result.queue,0);assert.equal(result.frame,0);
});
test('Panneaux : nouvelle cible remplace la précédente et mouvement réduit sans animation',async()=>{
  await page.emulateMedia({reducedMotion:'reduce'});
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card'),e=c._boardViews.get('departures').engine;for(const city of ['B','PARIS'])c.hass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'1',attributes:{flights:[{airport_city:city}]}}}};return {queue:e.queue.length,frame:e.frame,text:[...e.body.querySelectorAll('td:nth-child(2) .flap')].map(n=>n.dataset.char).join(''),calls:mockCalls.length};});assert.deepEqual(result,{queue:0,frame:0,text:'PARIS',calls:0});
});
test('Panneaux : cinq heures, six vol et maximum des colonnes sur toutes les lignes',async()=>{
  await page.emulateMedia({reducedMotion:'reduce'});
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card'),e=c._boardViews.get('departures').engine;const flights=mockHass.states['sensor.demo_departures'].attributes.flights.map((f,i)=>({...f,airport_city:i===29?'ABCDEFGHIJKLMNOPQRST':'PARIS',flight_number:'AB12345',status_text:i===29?'ANNULATION CONFIRMEE':'OK'}));c.hass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'30',attributes:{flights}}}};return {counts:[...e.body.children[0].children].map(td=>td.querySelectorAll('.flap').length),same:[...e.body.children[29].children].map(td=>td.querySelectorAll('.flap').length),flight:[...e.body.children[0].children[2].querySelectorAll('.flap')].map(n=>n.dataset.char).join(''),title:e.body.children[0].children[2].title};});assert.deepEqual(result.counts,[5,20,6,20]);assert.deepEqual(result.same,result.counts);assert.equal(result.flight,'AB1234');assert.equal(result.title,'AB12345');
});
test('Départs entièrement avant Arrivées, sans animations simultanées',async()=>{
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card');for(const id of ['sensor.demo_departures','sensor.demo_arrivals'])mockHass.states[id]={state:'1',attributes:{flights:[{airport_city:'A',flight_number:'A',status_text:'OK'}]}};c.hass=mockHass;c.shadowRoot.querySelector('.boards').scrollIntoView();});
  await page.emulateMedia({reducedMotion:'no-preference'});
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card'),s=c._boardScheduler;const states={...mockHass.states};for(const id of ['sensor.demo_departures','sensor.demo_arrivals'])states[id]={state:'1',attributes:{flights:[{airport_city:'D',flight_number:'A',status_text:'OK'}]}};c.hass={...mockHass,states};const trace=[];for(const t of [0,70,140,210,280]){cancelAnimationFrame(s.frame);s.tick(t);trace.push([...c._boardViews.values()].map(v=>v.engine.body.querySelector('td:nth-child(2) .flap').dataset.char));if(c.shadowRoot.querySelectorAll('[data-flipping]').length>1)throw Error('Animations simultanées');}c.remove();return {trace,frame:s.frame,calls:mockCalls.length};});assert.deepEqual(result.trace,[['B','A'],['C','A'],['D','A'],['D','A'],['D','B']]);assert.equal(result.frame,0);assert.equal(result.calls,0);
});
test('Chemin minimal dans les deux sens pour toutes les paires de la roue',async()=>{
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card');c.hass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'1',attributes:{flights:[{airport_city:'A',flight_number:'A',status_text:'OK'}]}},'sensor.demo_arrivals':{state:'0',attributes:{flights:[]}}}};});
  await page.emulateMedia({reducedMotion:'no-preference'});
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card'),e=c._boardViews.get('departures').engine;e.scroll.scrollIntoView();e.stop();const row=e.body.children[0],el=row.children[1].querySelector('.flap'),sequence=' ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789:-';e.visible=()=>true;let pairs=0;for(let a=0;a<sequence.length;a++)for(let b=0;b<sequence.length;b++){el.dataset.char=sequence[a];const forward=(b-a+sequence.length)%sequence.length,backward=(a-b+sequence.length)%sequence.length;const direction=forward<=backward?1:-1;e.queue=[{row,start:null,slots:[{el,target:sequence[b],start:0,last:0,steps:0}]}];let count=0;while(el.dataset.char!==sequence[b]&&count<sequence.length){e.tick(count*70);count++;if(el.dataset.char!==sequence[(a+direction*count+sequence.length*2)%sequence.length])throw Error('Ordre incorrect');}if(count!==Math.min(forward,backward))throw Error('Chemin non minimal');if(count&&el.dataset.direction!==(direction===1?'forward':'reverse'))throw Error('Sens incorrect');e.stop();pairs++;}c.remove();return {pairs,calls:mockCalls.length};});assert.equal(result.pairs,39*39);assert.equal(result.calls,0);
});
test('Proportions et police des panneaux identiques à celles des horloges',async()=>{
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card'),el=c.shadowRoot.querySelector('.flap'),style=getComputedStyle(el),clock=c._localClock.shadowRoot.querySelector('.digit'),cs=getComputedStyle(clock);return {height:parseFloat(style.height)/parseFloat(style.width),font:parseFloat(style.fontSize)/parseFloat(style.width),family:style.fontFamily,clock:cs.fontFamily};});assert.ok(Math.abs(result.height-1.45)<.01);assert.ok(Math.abs(result.font-1.35)<.01);assert.equal(result.family,result.clock);
});
test('Une cellule à la fois : heure, destination, vol, statut puis ligne suivante',async()=>{
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card');const flights=Array.from({length:2},()=>({time_scheduled_departure:'2026-10-03T10:00:00Z',airport_city:'A',flight_number:'A',status_text:'A'}));mockHass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'2',attributes:{flights}}}};c.hass=mockHass;c.shadowRoot.querySelector('.scroll').scrollIntoView();});
  await page.emulateMedia({reducedMotion:'no-preference'});
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card'),e=c._boardViews.get('departures').engine,s=c._boardScheduler;const flights=mockHass.states['sensor.demo_departures'].attributes.flights.map(f=>({...f,time_scheduled_departure:'2026-10-03T10:01:00Z',airport_city:'B',flight_number:'B',status_text:'B'}));c.hass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'2',attributes:{flights}}}};const trace=[];for(let time=0;time<3000&&e.queue.length;time+=70){cancelAnimationFrame(s.frame);s.tick(time);const cells=[...e.body.querySelectorAll('td')].filter(td=>td.querySelector('.flip-a,.flip-b'));if(cells.length>1)throw Error('Plusieurs cellules animées');if(cells.length){const cell=cells[0],key=cell.parentElement.sectionRowIndex+':'+cell.cellIndex;if(trace.at(-1)!==key)trace.push(key);}}const finished=e.queue.length===0;c.remove();return {trace,finished,calls:mockCalls.length};});assert.deepEqual(result.trace,['0:0','0:1','0:2','0:3','1:0','1:1','1:2','1:3']);assert.equal(result.finished,true);assert.equal(result.calls,0);
});
test('Aucun défilement horizontal avec destination et statut longs, desktop et mobile',async()=>{
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card');const flights=[{airport_city:'SAINT PETERSBURG',flight_number:'AB1234',status_text:'ESTIMATED DEPARTURE 17:45'}];c.hass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'1',attributes:{flights}},'sensor.demo_arrivals':{state:'1',attributes:{flights}}}};});
  for(const width of [1200,1080,820,390]){await page.setViewportSize({width,height:1000});const result=await page.evaluate(()=>[...document.querySelector('oasis-flightradar-card').shadowRoot.querySelectorAll('.scroll')].map(s=>({client:s.clientWidth,scroll:s.scrollWidth,flap:getComputedStyle(s.querySelector('.flap')).width,cells:[...s.querySelectorAll('td')].map(td=>({width:td.clientWidth,word:td.querySelector('.flap-word').getBoundingClientRect().width})),fit:[...s.querySelectorAll('tbody td')].every(td=>td.querySelector('.flap-word').getBoundingClientRect().width<=td.clientWidth-8)})));for(const r of result){assert.ok(r.scroll<=r.client+1,JSON.stringify({width,...r}));assert.equal(r.fit,true);}}
});
test('Secondes instantanées sur les deux horloges ; heures et minutes toujours animées',async()=>{
  await page.emulateMedia({reducedMotion:'no-preference'});
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card');const results=[c._localClock,c._airportClock].map(clock=>{clock._stop();clock._syncZone=()=>false;let fields=['12','34','59'];clock._formatter={formatToParts:()=>['hour','minute','second'].map((type,i)=>({type,value:fields[i]}))};clock._tick(false);fields=['12','35','00'];clock._tick(true);const minute=clock.shadowRoot.querySelectorAll('.minutes .flipping').length;const seconds=[...clock.shadowRoot.querySelectorAll('.seconds .digit')].map(d=>({animated:d.classList.contains('flipping'),top:d.querySelector('.top.base span').textContent,bottom:d.querySelector('.bottom.base span').textContent}));clock._stop();fields=['13','35','01'];clock._tick(true);const hour=clock.shadowRoot.querySelectorAll('.hours .flipping').length,secondAnimated=clock.shadowRoot.querySelectorAll('.seconds .flipping').length;clock._stop();return {minute,hour,seconds,secondAnimated};});c.remove();return {results,calls:mockCalls.length};});for(const r of result.results){assert.ok(r.minute>0);assert.ok(r.hour>0);assert.equal(r.secondAnimated,0);assert.deepEqual(r.seconds,[{animated:false,top:'0',bottom:'0'},{animated:false,top:'0',bottom:'0'}]);}assert.equal(result.calls,0);
});
test('Moteur sans animation : les deux tableaux changent instantanément, sans basculement',async()=>{
  const result=await page.evaluate(()=>{const c=mountCard();for(const v of c._boardViews.values())v.engine.animate=false;c.shadowRoot.querySelector('.boards').scrollIntoView();const flights=[{airport_city:'PARIS',flight_number:'AB1234',status_text:'LANDED'}];c.hass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'1',attributes:{flights}},'sensor.demo_arrivals':{state:'1',attributes:{flights}}}};const boards=[...c._boardViews.values()].map(v=>({animate:v.engine.animate,queue:v.engine.queue.length,city:[...v.engine.body.querySelector('td:nth-child(2)').querySelectorAll('.flap')].map(n=>n.dataset.char).join(''),flipping:v.engine.body.querySelectorAll('.flip-a,.flip-b').length}));const frame=c._boardScheduler.frame;c.remove();return {boards,frame,calls:mockCalls.length};});for(const b of result.boards)assert.deepEqual(b,{animate:false,queue:0,city:'PARIS',flipping:0});assert.equal(result.frame,0);assert.equal(result.calls,0);
});
test('Départs et Arrivées : mêmes caractères, panneaux, colonnes et espacements',async()=>{
  const result=await page.evaluate(()=>{const c=mountCard();c.hass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'1',attributes:{flights:[{airport_city:'PARIS',flight_number:'AF1234',status_text:'ESTIMATED DEPARTURE 18:45'}]}},'sensor.demo_arrivals':{state:'1',attributes:{flights:[{airport_city:'SAINT PETERSBURG',flight_number:'BA1234',status_text:'LANDED'}]}}}};const boards=[...c.shadowRoot.querySelectorAll('.scroll')].map(s=>{const f=getComputedStyle(s.querySelector('.flap'));return {font:f.font,fontSize:f.fontSize,width:f.width,height:f.height,cells:[...s.querySelectorAll('tbody tr:first-child td')].map(td=>({width:td.getBoundingClientRect().width,padding:getComputedStyle(td).padding,gap:getComputedStyle(td.querySelector('.flap-word')).gap,count:td.querySelectorAll('.flap').length})),horizontal:s.scrollWidth>s.clientWidth};});c.remove();return boards;});assert.deepEqual(result[0],result[1]);assert.deepEqual(result[0].cells.map(x=>x.count),[5,16,6,25]);assert.equal(result[0].horizontal,false);
});
test('Carte : cycle intermédiaire et séquence conservés, aucune rotation',async()=>{
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.evaluate(()=>{const c=mountCard();const flights=[{airport_city:'A',flight_number:'A',status_text:'A'}];mockHass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'1',attributes:{flights}},'sensor.demo_arrivals':{state:'1',attributes:{flights}}}};c.hass=mockHass;c.shadowRoot.querySelector('.boards').scrollIntoView();});
  await page.emulateMedia({reducedMotion:'no-preference'});
  const result=await page.evaluate(()=>{const c=document.querySelector('oasis-flightradar-card'),s=c._boardScheduler;const flights=[{airport_city:'D',flight_number:'B',status_text:'C'}];c.hass={...mockHass,states:{...mockHass.states,'sensor.demo_departures':{state:'1',attributes:{flights}},'sensor.demo_arrivals':{state:'1',attributes:{flights}}}};const trace=[];for(let t=0;t<4000&&s.engines.some(e=>e.queue.length);t+=70){cancelAnimationFrame(s.frame);s.tick(t);const v=s.engines.map(e=>[...e.body.querySelectorAll('td:nth-child(2) .flap')].map(n=>n.dataset.char).join(''));if(trace.length<5)trace.push(v);if(c.shadowRoot.querySelector('.flip-a,.flip-b'))throw Error('Rotation active');}const finished=s.engines.every(e=>!e.queue.length);const flags=s.engines.map(e=>({animate:e.animate,rotate:e.rotate}));c.remove();return {trace,finished,flags,calls:mockCalls.length};});assert.deepEqual(result.trace.slice(0,4),[['B','A'],['C','A'],['D','A'],['D','A']]);assert.equal(result.finished,true);assert.deepEqual(result.flags,[{animate:true,rotate:false},{animate:true,rotate:false}]);assert.equal(result.calls,0);
});
